### ISSUE TITLE
BreachingVR

### ISSUE THREAD

**Issue by BigSoftVideo** [BigSoftVideo/BigSoftVideo#8]
Reproduce one of Garfinkel's tutorial exercises (derived from Merleau-Ponty) in reality and VR:
- Breaching using inverted lenses via an HMD
- Breaching by inverting Virtual Reality in an HMD

Works on the HTC VIVE PRO with Windows 10.
Both variants make you sick very easily! 🤢

**Comment by skandilocks** [comment]
Prototype completed March 2020 for a workshop demo, which was cancelled because of the COVID-19 pandemic. Using _BreachingVR_ with a physically present group of people requires close contact with the VR headset and controllers. It has been tested locally, eg. by attempting to instruct a person in VR to physically navigate a room they can see through the headset camera (similar to augmented reality).

**Comment by BigSoftVideo** [comment]
[BreachingVR](https://github.com/Big-Video/BreachingVR) is now public and archived 
- [![DOI](https://zenodo.org/badge/283767362.svg)](https://zenodo.org/badge/latestdoi/283767362)
